### ISSUE TITLE
500 error when creating a new dataset

### ISSUE THREAD

**Issue by ajhool** [winwinwiki/api#371]
- [x] Go to https://wiki-edit.newimpact.care/and log in as yourself aidan@hool.co
  - [x] Go to https://wiki.newimpact.care/s/admin/app/kibana#/home?_g=()
     - [x] Set the "Space" to Admin in the top left of the screen
     - [ ] Find the application logs that might show a 500 message
  - [x] Go to this org page ( this is an org that no one is using) https://wiki-edit.newimpact.care/organizations/739804/data-sets and click +Add Data Set
    - [x] A form will appear -- enter a new data set name -- IMPORTANT -- if a match appears in typeahead change the name so that there is no match. The issue is with creating new datasets (and resources...a similar activity). Maybe a name like ztestData. -> **used ztestData**
   - [x] Deleted all data from description (ajhool decision)
   - [x]  Select Type closed ( just saves you a step)
   - [x] Open "Network" in firefox browser to view error
   - [x]  Click Save Changes
   - [x] A red error will appear and your dataset will not be saved
     **-> Request:** 
```
HEADERS:
POST /organization/739804/dataset HTTP/1.1
Host: backend-prod.newimpact.care
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
Content-Length: 124
user-auth-id: ey[REDACTED]
Cache-Control: private, must-revalidate, max-age=300
Origin: https://wiki-edit.newimpact.care
Referer: https://wiki-edit.newimpact.care/organizations/739804/data-sets
Connection: keep-alive
```
BODY:
```
{"type":"closed","url":"","dataSetCategory":{"categoryName":"ztestData","id":-1},"description":"","organizationId":"739804"}
````
     **-> Response:** 
```
HEADERS
HTTP/1.1 500 
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: user-auth-id
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json;charset=UTF-8
Date: Mon, 08 Mar 2021 18:27:40 GMT
Expires: 0
Pragma: no-cache
Set-Cookie: JSESSIONID=DC9E9535A95C75F7C72AAD55B82BBB49; Path=/; HttpOnly
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
Content-Length: 66
Connection: keep-alive
```
```
BODY
error occurred while creating organization data set
```

Same happens for resource...running to a meeting will add those steps after the meeting

**Comment by ajhool** [comment]
Pulled the error log from kibana by using the filter `apm-*-error`

It looks like there is a duplicate key issue:
```
          "message": "ERROR: duplicate key value violates unique constraint \"dataset_category_pkey\"\n  Detail: Key (id)=(10593) already exists.",
          "type": "org.postgresql.util.PSQLException"
```

Longer version: 
```
              "library_frame": true,
              "exclude_from_grouping": false,
              "filename": "JdkDynamicAopProxy.java",
              "line": {
                "number": 212
              },
              "module": "org.springframework.aop.framework",
              "function": "invoke"
            },
            {
              "library_frame": false,
              "exclude_from_grouping": false,
              "filename": "OrganizationDataSetServiceImpl.java",
              "line": {
                "number": 248
              },
              "function": "saveOrganizationDataSetCategory",
              "module": "com.winwin.winwin.service.impl"
            },
            {
              "library_frame": false,
              "exclude_from_grouping": false,
              "filename": "OrganizationDataSetServiceImpl.java",
              "line": {
                "number": 215
              },
              "module": "com.winwin.winwin.service.impl",
              "function": "setOrganizationDataSetCategory"
            },
            {
              "library_frame": false,
              "exclude_from_grouping": false,
              "filename": "OrganizationDataSetServiceImpl.java",
              "line": {
                "number": 153
              },
              "function": "constructOrganizationDataSet",
              "module": "com.winwin.winwin.service.impl"
            },
            {
              "library_frame": false,
              "exclude_from_grouping": false,
              "filename": "OrganizationDataSetServiceImpl.java",
              "line": {
                "number": 72
              },
              "module": "com.winwin.winwin.service.impl",
              "function": "createOrUpdateOrganizationDataSet"
            },
            {
              "library_frame": false,
              "exclude_from_grouping": false,
              "filename": "<generated>",
              "line": {
                "number": -1
              },
              "module": "com.winwin.winwin.service.impl",
              "function": "invoke"
            },
            {
              "library_frame": true,
              "exclude_from_grouping": false,
              "filename": "MethodProxy.java",
              "line": {
                "number": 218
              },
              "module": "org.springframework.cglib.proxy",
              "function": "invoke"
            },
            {
              "library_frame": true,
              "exclude_from_grouping": false,
              "filename": "CglibAopProxy.java",
              "line": {
                "number": 749
              },
              "module": "org.springframework.aop.framework",
              "function": "invokeJoinpoint"
            }
          ],
          "message": "ERROR: duplicate key value violates unique constraint \"dataset_category_pkey\"\n  Detail: Key (id)=(10593) already exists.",
          "type": "org.postgresql.util.PSQLException"
        }
      ],
      "culprit": "com.winwin.winwin.service.impl.OrganizationDataSetServiceImpl.saveOrganizationDataSetCategory(OrganizationDataSetServiceImpl.java:248)",
      "id": "d7a8b1c6a7108eb4ff76b48218439b27",
      "grouping_key": "fcd60ee44ea6201673595c125195626f"
    },
```

**Comment by ajhool** [comment]
Might be related to indexing of the data set category?

https://github.com/winwinwiki/api/blob/409d92b795265289f5bc721fd15cd14752869c62/src/main/java/com/winwin/winwin/entity/DataSetCategory.java

**Comment by ajhool** [comment]
The issue appears to be the SequenceGenerator in the DatasetCategory

https://www.logicbig.com/how-to/jpa/jpa-seq-generator-with-external-database.html

- [ ] How does mysql do "nextval()"? Is "SequenceGenerator" just querying the database for the highest PK and adding one -- that should be the case given that allocationSize = 1. Maybe that IS how it works, but the application has a value stored in its cache and manually uploading data to the database caused that value to be left behind. That doesn't quite make sense, but the fix would be an application reboot.
- [ ] Is there a "sequence" value that is stored within mysql that would match the @SequenceGenerator name value? ("dataset_category_generator")  -> https://github.com/winwinwiki/api/blob/master/src/main/java/com/winwin/winwin/entity/DataSetCategory.java
- [x] Is the "-1" entered by java being written to the database? **NO: It seems like the Entity classes have a private id field which is overwriten by SequenceGenerator**

**Comment by ajhool** [comment]
Sequence troubleshooting process:

Goal:

1. [x] Find the sequences in postgres. Confirm that the Increment = 1, which is what the frontend is expecting
2. [x] Get the current value of the sequence using a sql query
   ```
  SELECT currval('public.dataset_category_seq')
  
  ERROR: currval of sequence "dataset_category_seq" is not yet defined in this session
SQL state: 55000
   ```
3. Check the maximum value of the Primary Key in the database
  `SELECT MAX(id) FROM public.dataset_category`
  16984
4. [x] Induce the error by submitting the Create Workflow form 
5. [x] Compare the numbers in the currValue, maximum value, and error value
  -> The application appears to have started a new session with an old initial value (10605)
6. Update the current value of dataset_category_seq to be one higher than the maximum value in the dataset (16984) 
  `SELECT setval('dataset_category_seq', 16984);`

**Comment by BethRR** [comment]
ERROR:  currval of sequence "dataset_category_seq" is not yet defined in this session
SQL state: 55000

**Comment by ajhool** [comment]
This problem was resolved!

Okay, so the problem was that when the data was imported, the ids were already in the data which caused Postgres' sequence-generator to no update with the new resources. Usually, when you insert, say, 1234 resources into the database the id's would be generated using the sequence generator and the sequence value would be: 1234 after all rows had been inserted. By using a direct import, the sequence generator was not triggered, so the sequence value in the database did not update correctly.

The application queries the sequence generator every time before inserting new data.

The Start Value in the CREATE SEQUENCE SQL command can be used to offset an initial data dump, and there was an attempt at using the Start value; however, the start value was set too low. It was set below the number of rows that were initially inserted (eg. if 1234 rows were initially inserted, the start value had incorrectly been set to 1200 ). Thus, when the Spring application was attempting to insert a new row, it was trying to set the id to 1200+1, 1201, which already existed in the DB.

Step 1. Find maximum value of the id in the table
```
SELECT MAX(id) FROM public.TABLE_NAME
```
Use the above value, say 1234 in the below query

Step 2. Update the corresponding sequence with the maximum value found in Step 1. "nextVal()" will return that value + 1.
```
`SELECT setval('name_of_the_sequence', 1234);`
```

The two tables updated in this process were:

`dataset_category`

`resource_category`
